# Server configuration
server:
  port: 9000

# App config
spring:
  main:
    banner-mode: off

# Logging config
logging:
  level:
    root: OFF
    pl.uglywarthog.prometheus: INFO

# Actuator config
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: prometheus
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enable:
      all: false
      test: true

